AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
